
package com.rs.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://service.rs.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.rs.model.ObjectFactory.class,
    com.rs.service.ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @param book
     * @return
     *     returns com.rs.service.Book
     */
    @WebMethod(action = "http://service.rs.com/registerBook")
    @WebResult(name = "RegisterBookOut", targetNamespace = "http://model.rs.com", partName = "param")
    public Book registerBook(
        @WebParam(name = "RegisterBookIn", targetNamespace = "http://model.rs.com", partName = "book")
        Book book);

    /**
     * 
     * @param isbn
     * @return
     *     returns com.rs.service.Book
     */
    @WebMethod(action = "http://service.rs.com/searchBook")
    @WebResult(name = "SearchBookOut", targetNamespace = "http://model.rs.com", partName = "param")
    public Book searchBook(
        @WebParam(name = "SearchBookIn", targetNamespace = "http://service.rs.com", partName = "isbn")
        String isbn);

}
